"""Backtest runner (PLAN 10.3). Replays each setup over history and simulates
trades with look-ahead-free execution.

Signals are generated by the SAME scanner functions used live (no research/production
divergence). To stay fast, each scanner is only invoked on dates that pass a cheap
vectorized precondition; the scanner then makes the full decision on the sliced,
point-in-time frame.
"""

from __future__ import annotations

from dataclasses import asdict
from datetime import date

import pandas as pd

from analyzer.backtest.engine import simulate_trade
from analyzer.config import Config, get_config
from analyzer.logging_setup import get_logger
from analyzer.setups import SCANNERS
from analyzer.setups.base import (
    SETUP_A,
    SETUP_B,
    SETUP_C,
    SETUP_D,
    SETUP_E,
    get_active_setups,
)
from analyzer.signals.levels import compute_levels

log = get_logger(__name__)

# Bars to look forward when simulating (entry window + time stop + buffer).
_LOOKFORWARD = 45

# setup id -> config.setups key (for per-setup options like allowed_regimes).
_SETUP_CFG_KEY = {
    SETUP_A: "breakout",
    SETUP_B: "pullback",
    SETUP_C: "mean_reversion",
    SETUP_D: "squeeze",
}


def _setup_key(setup: str) -> str:
    return _SETUP_CFG_KEY.get(setup, setup)


def _load_symbol_frame(repo, symbol: str) -> pd.DataFrame:
    return repo.query_df(
        """
        SELECT a.symbol, a.date, a.open, a.high, a.low, a.close, a.volume,
               r.delivery_pct,
               i.ema20, i.ema50, i.sma200, i.adx, i.rsi, i.macd, i.macd_hist,
               i.atr, i.atr_pct, i.bb_width_pctile, i.vol_ratio, i.rs_pctile,
               i.roc20, i.roc60, i.dist_52wh, i.supertrend, i.in_base, i.base_days,
               i.wk_gate_trend, i.wk_gate_mr
        FROM prices_adj a
        JOIN indicators_daily i ON i.symbol = a.symbol AND i.date = a.date
        LEFT JOIN prices_raw r ON r.symbol = a.symbol AND r.date = a.date
        WHERE a.symbol = ?
        ORDER BY a.date
        """,
        [symbol],
    )


def _precondition_mask(df: pd.DataFrame, setup: str, cfg: Config) -> pd.Series:
    """Cheap necessary (not sufficient) condition to shortlist candidate dates."""
    s = cfg.setups
    if setup == SETUP_A:
        lvl = df["high"].shift(1).rolling(s["breakout"]["high_lookback"]).max()
        return (df["close"] > lvl) & (df["vol_ratio"] >= s["breakout"]["vol_mult_min"])
    if setup == SETUP_B:
        return (
            (df["close"] > df["sma200"])
            & (df["close"] > df["high"].shift(1))
            & (df["vol_ratio"] < 1.2)
        )
    if setup == SETUP_C:
        return (df["rsi"] < s["mean_reversion"]["rsi_max"]) & (df["adx"] < 20)
    if setup == SETUP_D:
        return (
            (df["bb_width_pctile"].shift(1) <= s["squeeze"]["bb_width_pctile_max"])
            & (df["vol_ratio"] >= s["squeeze"]["vol_mult_min"])
        )
    if setup == SETUP_E:
        # Requires a results_recent column injected on the frame (R4 calendar).
        if "results_recent" not in df.columns:
            return pd.Series(False, index=df.index)
        return df["results_recent"].fillna(False).astype(bool) & (
            df["vol_ratio"] >= s["earnings_momentum"]["vol_mult_min"]
        )
    return pd.Series(False, index=df.index)


def run_backtest(
    repo,
    cfg: Config | None = None,
    setups: list[str] | None = None,
    start: date | None = None,
    end: date | None = None,
    apply_weekly_gate: bool = False,
    respect_regime: bool = True,
    symbols: list[str] | None = None,
    frames_cache: dict[str, pd.DataFrame] | None = None,
    signal_filter=None,
) -> dict[str, pd.DataFrame]:
    """Return {setup_id: trades DataFrame} over [start, end].

    ``apply_weekly_gate`` enables the §7.6 weekly filter (for ablation, task 5.6).
    ``respect_regime`` only takes signals whose setup is active in that day's regime.
    ``symbols`` restricts the scan (default: every symbol with indicators).

    Liquidity gate: a signal is only taken if the stock's rolling 20-day median
    traded value (volume x close, adjustment-invariant) meets the Layer-0
    tradability floor at the SIGNAL date — keeps illiquid junk out of results
    without look-ahead.
    """
    cfg = cfg or get_config()
    setups = setups or [SETUP_A, SETUP_B, SETUP_C, SETUP_D]
    min_traded_value = cfg.tradability.min_median_traded_value_cr * 1e7  # cr -> INR

    regime_df = repo.query_df("SELECT date, regime FROM regime_daily")
    regime_map = dict(zip(pd.to_datetime(regime_df["date"]), regime_df["regime"]))

    if symbols is None:
        symbols = repo.query_df(
            "SELECT DISTINCT symbol FROM indicators_daily ORDER BY symbol"
        )["symbol"].tolist()

    results: dict[str, list[dict]] = {s: [] for s in setups}

    for symbol in symbols:
        if frames_cache is not None and symbol in frames_cache:
            df = frames_cache[symbol]
        else:
            df = _load_symbol_frame(repo, symbol)
            if frames_cache is not None:
                frames_cache[symbol] = df
        if len(df) < 260:
            continue
        df = df.reset_index(drop=True)
        dts = pd.to_datetime(df["date"])
        # Rolling liquidity (volume x close is invariant to CA adjustment).
        liq = (df["volume"] * df["close"]).rolling(20, min_periods=10).median().to_numpy()

        for setup in setups:
            scanner = SCANNERS[setup]
            allowed_regimes = cfg.setups.get(_setup_key(setup), {}).get("allowed_regimes")
            mask = _precondition_mask(df, setup, cfg).fillna(False).to_numpy()
            cand_idx = [i for i in range(260, len(df) - 1) if mask[i]]
            for idx in cand_idx:
                sig_date = df.iloc[idx]["date"].date() if hasattr(df.iloc[idx]["date"], "date") else df.iloc[idx]["date"]
                if start and sig_date < start:
                    continue
                if end and sig_date > end:
                    continue
                if pd.isna(liq[idx]) or liq[idx] < min_traded_value:
                    continue

                regime = regime_map.get(dts.iloc[idx], "NEUTRAL")
                if respect_regime and setup not in get_active_setups(regime):
                    continue
                if allowed_regimes and regime not in allowed_regimes:
                    continue
                # Optional research overlay (e.g. point-in-time quality gate).
                if signal_filter is not None and not signal_filter(symbol, sig_date):
                    continue
                if apply_weekly_gate:
                    row = df.iloc[idx]
                    gate = row["wk_gate_mr"] if setup == SETUP_C else row["wk_gate_trend"]
                    if not bool(gate):
                        continue

                window = df.iloc[: idx + 1]
                raw = scanner(window, cfg.setups)
                if raw is None:
                    continue
                levels = compute_levels(raw, cfg.signals)
                if levels is None:
                    continue

                signal = {
                    "symbol": symbol, "setup": setup, "date": sig_date,
                    "entry_aggressive": levels.entry_aggressive,
                    "stop_loss": levels.stop_loss, "t1": levels.t1, "t2": levels.t2,
                }
                future = df.iloc[idx + 1 : idx + 1 + _LOOKFORWARD]
                tr = simulate_trade(signal, future, cfg.signals, cfg.backtest)
                rec = asdict(tr)
                rec["regime"] = regime
                results[setup].append(rec)

    out = {}
    for setup, recs in results.items():
        tdf = pd.DataFrame(recs)
        out[setup] = tdf
        n_entered = int(tdf["entered"].sum()) if not tdf.empty else 0
        log.info("backtest_setup_done", setup=setup, signals=len(tdf), entered=n_entered)
    return out
